platform :ios, '13.0'
use_frameworks!

def pods
  
  # Quality
  pod 'SwiftLint'
  
  # Rx
  pod 'RxSwift', '~> 5.1.1'
  pod 'RxOptional'
  pod 'RxDataSources'
  
  # Database
  pod 'RealmSwift', '~> 10.5.2'
  
  # Firebase
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'FirebaseAuth'
  
  # Login
  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit'
  
  # Animation
  pod 'lottie-ios'
  
end

target 'ios-starter' do
  pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        # Set minimum deloyment target to avoid warnings
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
        
        # Disable code signing for pods
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
        
        # Silence pods warnings
        target.build_configurations.each do |config|
            config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
        end
        
        # Silence build crash https://developer.apple.com/forums/thread/734636
        #target.build_configurations.each do |config|
         #   xcconfig_path = config.base_configuration_reference.real_path
          #  xcconfig = File.read(xcconfig_path)
           # xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
            #File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
        #end
    end
end
